[package]
name = "mks-servo42"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A no_std library for encoding commands to a mks_servo motor"

repository = "https://github.com/richo/mks-servo42"


[dev-dependencies]
serial = "0.4.0"
